services:

  nginx:
    image: nginx:latest
    container_name: web_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./website1:/var/www/website1
      - ./website2:/var/www/website2
    depends_on:
      - nodered
    networks:
      - web_network

  nodered:
    image: nodered/node-red:latest
    container_name: web_nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
    networks:
      - web_network

  mariadb:
    image: mariadb:latest
    container_name: web_mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - web_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: web_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    depends_on:
      - mariadb
    networks:
      - web_network

networks:
  web_network:

volumes:
  mariadb_data:
